### ISSUE TITLE
Function.sublime-completions

### ISSUE THREAD

**Issue by KES-ke** [deathaxe/sublime-s840d#1]
Hi Deathaxe,
I load you Repository and played a little bit around. It's really cool, great job.
In a NC-Program I tried to work with the function GetfreeLoc() but it worked not correctly. I looked in the file Function.sublime-completions, for the trigger. Is it possible that here some commas missing. I'm not so familiar with sublime programming, may you can check it and give me an answer.

**Comment by deathaxe** [comment]
Thanks for reporting.

Added the missing curly braces and merged it to a new release 1.5.1

**Comment by KES-ke** [comment]
Hallo, ich finde dein Package echt super und würde gerne noch ein paar Sachen nachfragen bzw. Ich habe noch ein paar Ideen. Hast du vielleicht Lust mit mir in Kontakt zu treten? Würde mich sehr freuen. Ich weiß leider nicht wie ich dir direkt eine Mail schicken kann.



Mit freundlichen Grüßen
Klaus Eichhorn


-------- Ursprüngliche Nachricht --------
Von: deathaxe <notifications@github.com>
Datum: 25.05.17 15:02 (GMT+01:00)
An: deathaxe/sublime-s840d <sublime-s840d@noreply.github.com>
Cc: Klaus Eichhorn <kes_ke@w-kes.de>, Author <author@noreply.github.com>
Betreff: Re: [deathaxe/sublime-s840d] Function.sublime-completions (#1)


Thanks for reporting.

Added the missing curly braces and merged it to a new release 1.5.1

**Comment by deathaxe** [comment]
Ich bin regelmäßig auf GitHub unterwegs - oft regelmäßiger als auf meiner E-Mail :-)

Ein **Issue** kann auch eine Idee sein, die diskutiert wird und auf deren Basis dann eine Entwicklung stattfindet.

**Comment by deathaxe** [comment]
Ansonsten bin ich unter robert.geisler@starrag.com zu erreichen.
