### ISSUE TITLE
Highlighting NC-Variables/Machine Data not working

### ISSUE THREAD

**Issue by ramooon1** [deathaxe/sublime-s840d#2]
Hi deathaxe,

I have an issue that highlighting global variable like `$AC_`, `$P_ `etc. I think every variable begins with "**$**" is affected. 
I copied the regex from "**_s840d_gcode.sublime-syntax_" line 1584** to validate it and works. So, the error might be somewhere else.

![Screenshot 2022-02-07 115409](https://user-images.githubusercontent.com/44432184/152861754-416da6c9-1c9d-4e9d-baf0-458427519dbc.png)

Note:
OS:               Win10 (19041)
ST-Version:   4126

**Comment by deathaxe** [comment]
You probably want to create a user override of Monokai.sublime-color-scheme to assign desired colors.

1. Call _UI: Customize Color Scheme_ from Command Palette
2. Paste the following content into the right view and edit it to your needs.

```json
// Documentation at https://www.sublimetext.com/docs/color_schemes.html
{
	"variables":
	{
	},
	"globals":
	{
	},
	"rules":
	[
		{
			"name": "Support Library Variables",
			"scope": "support.variable",
			"foreground": "var(orange)",
		},
		{
			"name": "Support Library Variables Punctuation",
			"scope": "support.variable punctuation.definition.variable",
			"foreground": "color(var(orange) a(60%))",
		}
	]
}
```

**Comment by PhantomToast** [comment]
Hey Deathaxe

This plug in has been absolutely fantastic while i was workin with the
Siemens 840d ,

I was working for GROB

Unfortunately i have moved on to a different feild now

But thanks so much for your work

Kind Regards Chirs

**Comment by deathaxe** [comment]
Nice to hear it useful.
